apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: tasks
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - name: web-tasks
      protocol: TCP
      port: 8000
      targetPort: 8000